/// 术语词条
class TermEntry {
  const TermEntry({
    required this.definition,
    required this.condition,
    required this.implication,
  });

  /// 定义
  final String definition;

  /// 成立条件
  final String condition;

  /// 吉凶含义
  final String implication;
}

/// 六爻断卦术语词典（约 80 条）。
///
/// 规则口径以《增删卜易》为主干，三刑、相害等按《卜筮正宗》补充。
/// 化扶、冲起、冲实、冲脱等为相近概念的别称，词条中说明归并关系。
class TermGlossary {
  TermGlossary._();

  static TermEntry? lookup(String term) => entries[term];

  static const Map<String, TermEntry> entries = {
    // ── 日月旺衰 ──
    '临月建': TermEntry(
        definition: '爻支与月建相同',
        condition: '爻之地支即当月月建',
        implication: '得令而旺，诸爻中最有力，吉凶皆应之速'),
    '月破': TermEntry(
        definition: '爻被月建所冲',
        condition: '月建与爻支六冲',
        implication: '大凶之象，破而无用；出月实破、逢合之日可解'),
    '月生': TermEntry(
        definition: '月建五行生爻',
        condition: '月建之五行生爻之五行',
        implication: '得月气相助，爻旺而有用'),
    '月克': TermEntry(
        definition: '月建五行克爻',
        condition: '月建之五行克爻之五行',
        implication: '受月气压制，爻衰而乏力'),
    '旺': TermEntry(
        definition: '旺相休囚死之首',
        condition: '爻五行与月令相同（当令）',
        implication: '气势最盛，用神旺则事成'),
    '相': TermEntry(
        definition: '次旺之位',
        condition: '月令五行生爻（我受月生）',
        implication: '得生有气，仅次于旺'),
    '休': TermEntry(
        definition: '休息无力之位',
        condition: '爻五行生月令（泄气于月）',
        implication: '气泄而休，不堪重任'),
    '囚': TermEntry(
        definition: '被困之位',
        condition: '爻五行克月令（逆令而战）',
        implication: '力竭被囚，难有作为'),
    '死': TermEntry(
        definition: '衰绝之位',
        condition: '月令五行克爻',
        implication: '受克至衰，最弱之地'),
    '临日建': TermEntry(
        definition: '爻支与日辰相同',
        condition: '爻之地支即当日日支',
        implication: '得日辰之力，当日之权最重'),
    '日扶': TermEntry(
        definition: '日辰与爻同五行',
        condition: '日支五行与爻相同而支不同',
        implication: '如兄弟帮扶，爻得日辰之助'),
    '日生': TermEntry(
        definition: '日辰五行生爻',
        condition: '日支之五行生爻之五行',
        implication: '得日辰生助，衰爻可起'),
    '日克': TermEntry(
        definition: '日辰五行克爻',
        condition: '日支之五行克爻之五行',
        implication: '受日辰之克，爻力受损'),
    '得月令': TermEntry(
        definition: '即临月建、当令而旺',
        condition: '见「临月建」「旺」',
        implication: '同临月建'),
    '得日扶': TermEntry(
        definition: '即临日建或日扶',
        condition: '见「临日建」「日扶」',
        implication: '同日扶'),

    // ── 空亡 ──
    '旬空': TermEntry(
        definition: '爻支落在本旬空亡',
        condition: '以日干支定旬，本旬所缺二支为空',
        implication: '空而不受生克，吉凶皆悬而未决'),
    '真空': TermEntry(
        definition: '到底无用之空',
        condition: '休囚安静之爻逢旬空',
        implication: '真空到底不能用，所占之事难成'),
    '假空': TermEntry(
        definition: '暂时之空，出空即用',
        condition: '旺相之爻或动爻逢旬空',
        implication: '出空、填实之日即有用，吉凶应于彼时'),
    '动不为空': TermEntry(
        definition: '动爻虽空不作空论',
        condition: '发动之爻落旬空',
        implication: '动则有用，出空之日应事'),
    '旺不为空': TermEntry(
        definition: '旺相之爻虽空不作空论',
        condition: '旺相之爻落旬空',
        implication: '旺不为空，填实之日应事'),
    '冲空': TermEntry(
        definition: '日辰冲旬空之爻',
        condition: '空亡之爻逢日辰六冲',
        implication: '冲空则起，空爻因冲而起用'),
    '填实': TermEntry(
        definition: '空亡之支当值',
        condition: '值空亡之支的日月到来',
        implication: '空爻填实则有用，常为应期'),
    '出空': TermEntry(
        definition: '出了旬空的时段',
        condition: '过本旬之后或值本支之日',
        implication: '假空出空即有用，常为应期'),

    // ── 墓绝 ──
    '入日墓': TermEntry(
        definition: '爻入日辰之墓库',
        condition: '日支为爻五行之墓（金墓丑、木墓未、火墓戌、水土墓辰）',
        implication: '如人入狱、物入库，闭而不用；冲墓之日出'),
    '入月墓': TermEntry(
        definition: '爻入月建之墓库',
        condition: '月建为爻五行之墓',
        implication: '整月受困，冲墓开库之日应事'),
    '入动墓': TermEntry(
        definition: '爻随动爻入墓',
        condition: '卦中动爻之支为本爻五行之墓',
        implication: '被动爻收入墓库，受制难展'),
    '入变墓': TermEntry(
        definition: '动爻化出之变爻为其墓库，即化墓',
        condition: '见「化墓」',
        implication: '同化墓'),
    '出墓': TermEntry(
        definition: '墓库被冲开',
        condition: '入墓之爻逢日辰冲其墓库',
        implication: '开库而出，受困之事解'),
    '临绝': TermEntry(
        definition: '爻临绝地',
        condition: '日辰或月建为爻五行之绝地（金绝寅、木绝申、火绝亥、水土绝巳）',
        implication: '气数将尽；逢生则绝处逢生'),

    // ── 合冲刑害 ──
    '合住': TermEntry(
        definition: '动爻被合而绊住',
        condition: '动爻与他爻或日辰六合',
        implication: '动而被绊，吉凶皆迟；冲开之日应'),
    '合起': TermEntry(
        definition: '静爻被合而起用',
        condition: '静爻被动爻或日辰六合',
        implication: '静而得合则起，为吉'),
    '合绊': TermEntry(
        definition: '两动爻相合互绊',
        condition: '两动爻之支六合',
        implication: '彼此牵绊，皆难施展；冲开之日应'),
    '冲开': TermEntry(
        definition: '合处逢冲而解',
        condition: '相合之爻逢日辰冲其一',
        implication: '合解绊除，事得进展'),
    '相冲': TermEntry(
        definition: '爻与爻六冲',
        condition: '两爻之支六冲且至少一爻动',
        implication: '冲则动荡不安，主散主变'),
    '三合局': TermEntry(
        definition: '三支会成一局',
        condition: '申子辰水、亥卯未木、寅午戌火、巳酉丑金，卦中三支齐备且至少两爻动',
        implication: '合局之力最大，局之五行论吉凶'),
    '三合成局': TermEntry(
        definition: '借日月凑成三合局',
        condition: '两动爻与日辰或月建凑齐三合',
        implication: '同三合局，得外力而成'),
    '半合': TermEntry(
        definition: '三合局中含旺支的两支之合',
        condition: '如申子、子辰（含旺支子）且有动爻',
        implication: '合力次于三合局，待全局之日更佳'),
    '三刑': TermEntry(
        definition: '寅巳申、丑戌未、子卯相刑（《卜筮正宗》）',
        condition: '刑组之支两两相遇且有动爻',
        implication: '主刑伤官非，参考为辅不作主断'),
    '相刑': TermEntry(
        definition: '两支相刑',
        condition: '同三刑组内两支，或辰午酉亥自刑',
        implication: '同三刑，低权重参考'),
    '相害': TermEntry(
        definition: '六害（《卜筮正宗》）',
        condition: '子未、丑午、寅巳、卯辰、申亥、酉戌相遇且有动爻',
        implication: '主暗中损害，参考为辅'),

    // ── 动静动变 ──
    '暗动': TermEntry(
        definition: '静爻被日辰冲起',
        condition: '旺相之静爻逢日辰六冲',
        implication: '如人暗中行事，吉者暗中得助，凶者暗里生患'),
    '日破': TermEntry(
        definition: '休囚静爻被日冲散',
        condition: '休囚之静爻逢日辰六冲',
        implication: '冲散无用，凶'),
    '日冲': TermEntry(
        definition: '日辰冲爻之统称',
        condition: '日支与爻支六冲',
        implication: '旺者暗动、衰者日破、空者冲空'),
    '冲起': TermEntry(
        definition: '爻因冲而起用之统称',
        condition: '见「暗动」「冲空」',
        implication: '同暗动、冲空则起'),
    '冲实': TermEntry(
        definition: '空爻被冲而实',
        condition: '见「冲空」',
        implication: '同冲空'),
    '冲散': TermEntry(
        definition: '休囚动爻被日冲散',
        condition: '休囚之动爻逢日辰六冲',
        implication: '动而被散，事有始无终'),
    '冲脱': TermEntry(
        definition: '合处逢冲而脱之别称',
        condition: '见「冲开」',
        implication: '同冲开'),
    '独发': TermEntry(
        definition: '六爻中唯一爻动',
        condition: '卦中仅一个动爻',
        implication: '事应专一，此爻为断卦枢机'),
    '独静': TermEntry(
        definition: '五爻皆动唯一爻静',
        condition: '卦中五个动爻一个静爻',
        implication: '乱中取静，此静爻为断卦枢机'),
    '化进神': TermEntry(
        definition: '动爻化出同五行顺行之支',
        condition: '寅化卯、巳化午、申化酉、亥化子、丑辰未戌递进',
        implication: '愈进愈旺，吉者更吉、凶者更凶'),
    '化退神': TermEntry(
        definition: '动爻化出同五行逆行之支',
        condition: '卯化寅、午化巳、酉化申、子化亥等',
        implication: '渐退渐衰，事势渐消'),
    '化扶': TermEntry(
        definition: '变爻与本爻同五行相扶之统称',
        condition: '同五行之化必为进神或退神，见各条',
        implication: '进则增力，退则减力'),
    '回头生': TermEntry(
        definition: '变爻回头生本爻',
        condition: '变爻五行生动爻五行',
        implication: '化出生我，愈动愈旺，吉'),
    '回头克': TermEntry(
        definition: '变爻回头克本爻',
        condition: '变爻五行克动爻五行',
        implication: '自招其克，大凶之化'),
    '化泄': TermEntry(
        definition: '本爻生变爻而泄气',
        condition: '动爻五行生变爻五行',
        implication: '动而泄气，力量渐减'),
    '化空': TermEntry(
        definition: '变爻落旬空',
        condition: '变爻之支在本旬空亡',
        implication: '化出成空，出空之日应事'),
    '化破': TermEntry(
        definition: '变爻被月建冲破',
        condition: '变爻之支与月建六冲',
        implication: '化出遭破，所化无用'),
    '化墓': TermEntry(
        definition: '动爻化入自墓',
        condition: '变爻之支为动爻五行之墓库',
        implication: '动而入墓自困，凶；冲墓之日出'),
    '化绝': TermEntry(
        definition: '动爻化入绝地',
        condition: '变爻之支为动爻五行之绝地',
        implication: '化至绝地，气数将尽，凶'),
    '化合': TermEntry(
        definition: '变爻回头合本爻',
        condition: '变爻之支与动爻六合',
        implication: '化出羁绊，动而被合住；冲开之日应'),
    '化冲': TermEntry(
        definition: '变爻回头冲本爻',
        condition: '变爻之支与动爻六冲',
        implication: '自化相冲，动荡不安'),

    // ── 生克 ──
    '动爻生': TermEntry(
        definition: '动爻来生本爻',
        condition: '动爻五行生本爻五行',
        implication: '得动爻生扶，吉'),
    '动爻克': TermEntry(
        definition: '动爻来克本爻',
        condition: '动爻五行克本爻五行',
        implication: '受动爻克制，凶'),
    '动爻扶': TermEntry(
        definition: '同五行动爻拱扶',
        condition: '动爻与本爻五行相同',
        implication: '如兄弟并肩，本爻得助'),
    '生': TermEntry(
        definition: '五行相生',
        condition: '金生水、水生木、木生火、火生土、土生金',
        implication: '生我者有助'),
    '克': TermEntry(
        definition: '五行相克',
        condition: '金克木、木克土、土克水、水克火、火克金',
        implication: '克我者为制'),
    '泄': TermEntry(
        definition: '我生者泄我之气',
        condition: '本爻生他爻',
        implication: '气泄而力减'),
    '耗': TermEntry(
        definition: '我克者耗我之力',
        condition: '本爻克他爻',
        implication: '战而耗力'),
    '扶': TermEntry(
        definition: '同五行相帮',
        condition: '两爻五行相同',
        implication: '比和相扶'),
    '拱': TermEntry(
        definition: '扶之别称',
        condition: '见「扶」「动爻扶」',
        implication: '同扶'),
    '制': TermEntry(
        definition: '克之受制表述',
        condition: '见「克」「动爻克」',
        implication: '被克则受制'),
    '贪生忘克': TermEntry(
        definition: '动爻贪生而忘克',
        condition: '动爻既克本爻又生另一动爻',
        implication: '舍克就生，本爻之克得解，吉'),
    '贪合忘生': TermEntry(
        definition: '动爻贪合而忘生',
        condition: '应生本爻之动爻被合住',
        implication: '合处不生，本爻失其生扶'),
    '贪合忘克': TermEntry(
        definition: '动爻贪合而忘克',
        condition: '应克本爻之动爻被合住',
        implication: '合处不克，本爻之克得解，吉'),
    '连续相生': TermEntry(
        definition: '动爻递相生',
        condition: '三个及以上动爻依次相生',
        implication: '气脉相连，生生不息，大吉'),
    '连续相克': TermEntry(
        definition: '动爻递相克',
        condition: '三个及以上动爻依次相克',
        implication: '祸患相连，大凶'),

    // ── 六亲 ──
    '用神': TermEntry(
        definition: '所占之事的代表爻',
        condition: '按所占之事取六亲：占财取妻财、占官取官鬼等，本卦由用户点选',
        implication: '断卦之枢纽，用神旺衰定成败'),
    '用神(伏)': TermEntry(
        definition: '用神不上卦，取伏神为用',
        condition: '所需六亲不现，于本宫首卦取同位伏神',
        implication: '伏而待出，飞神空破之日得出'),
    '原神': TermEntry(
        definition: '生用神之爻',
        condition: '六亲相生中生用神者',
        implication: '用神之根，原神旺动则用神有源'),
    '忌神': TermEntry(
        definition: '克用神之爻',
        condition: '六亲相克中克用神者',
        implication: '用神之敌，忌神旺动则事凶'),
    '仇神': TermEntry(
        definition: '克原神、生忌神之爻',
        condition: '六亲循环中克原神者',
        implication: '助纣为虐，动则原神受伤'),
    '闲神': TermEntry(
        definition: '与用神无直接生克之爻',
        condition: '非用原忌仇之其余六亲',
        implication: '平时无碍，动化后或参战局'),
    '用神两现': TermEntry(
        definition: '用神六亲在卦中出现两处',
        condition: '两爻同为用神六亲',
        implication: '舍此取彼：取动爻、旺爻或临世应者'),
    '世爻': TermEntry(
        definition: '代表求测人自身之爻',
        condition: '按卦宫世位而定',
        implication: '自占以世为用'),
    '应爻': TermEntry(
        definition: '代表他人他事之爻',
        condition: '与世爻相隔三位',
        implication: '占他人事以应为参'),

    // ── 伏藏飞神 ──
    '伏神': TermEntry(
        definition: '不上卦而伏藏之六亲',
        condition: '本卦所缺六亲取本宫首卦同位之爻',
        implication: '伏而不现，得出方有用'),
    '飞神': TermEntry(
        definition: '伏神所伏之位的本卦爻',
        condition: '伏神所在爻位的本卦之爻',
        implication: '飞伏生克定伏神吉凶'),
    '飞生伏': TermEntry(
        definition: '飞神生伏神',
        condition: '飞神五行生伏神五行',
        implication: '伏神得长生，吉'),
    '飞克伏': TermEntry(
        definition: '飞神克伏神',
        condition: '飞神五行克伏神五行',
        implication: '伏神受压难出，凶'),
    '伏生飞': TermEntry(
        definition: '伏神生飞神',
        condition: '伏神五行生飞神五行',
        implication: '伏神泄气于飞神，我怀才而助人'),
    '伏克飞': TermEntry(
        definition: '伏神克飞神',
        condition: '伏神五行克飞神五行',
        implication: '伏神出暴有力，能自出而用'),
    '伏神得出': TermEntry(
        definition: '伏神可出而用',
        condition: '飞神空亡、被日冲，或值伏神之日',
        implication: '伏藏之物得见天日，吉'),
    '伏神受制': TermEntry(
        definition: '伏神受制难出',
        condition: '飞克伏又逢日月克伏神',
        implication: '终难出用，所求难得'),

    // ── 特殊作用 ──
    '日合': TermEntry(
        definition: '日辰与爻六合',
        condition: '日支与爻支六合',
        implication: '合静爻为合起（吉），合动爻为合绊（迟滞）'),
    '月合': TermEntry(
        definition: '月建与爻六合',
        condition: '月建与爻支六合',
        implication: '同日合，月内之绊'),
    '太岁入爻': TermEntry(
        definition: '爻临太岁（年支）',
        condition: '爻支与流年地支相同',
        implication: '事关久远、官事、年内之应'),

    // ── 卦象变化 ──
    '六冲卦': TermEntry(
        definition: '六爻逐位相冲之卦',
        condition: '八纯卦及天雷无妄、雷天大壮',
        implication: '主散、主快：占病吉、占婚凶、久事散'),
    '六合卦': TermEntry(
        definition: '六爻逐位相合之卦',
        condition: '泰、否、节、豫、困、贲、旅、复八卦',
        implication: '主成、主缓：占婚吉、占病凶、事多迟滞'),
    '游魂卦': TermEntry(
        definition: '各宫第七卦',
        condition: '五爻复变之卦',
        implication: '主心神不定、外出行走、魂不守宅'),
    '归魂卦': TermEntry(
        definition: '各宫第八卦',
        condition: '游魂再变内卦复原',
        implication: '主返本还原、出行而归、事归故处'),
    '卦变六合': TermEntry(
        definition: '变卦为六合卦',
        condition: '动变之后成六合',
        implication: '渐入佳境，先难后成'),
    '卦变六冲': TermEntry(
        definition: '变卦为六冲卦',
        condition: '动变之后成六冲',
        implication: '先合后散，事将不终'),
    '伏吟': TermEntry(
        definition: '变卦纳支与本卦相同',
        condition: '内卦或外卦动而变后纳支不变（如乾震互变）',
        implication: '呻吟忧虑，欲动不能，事多迁延'),
    '反吟': TermEntry(
        definition: '变卦纳支与本卦逐位相冲',
        condition: '内卦或外卦动而变后纳支逐位六冲（如巽坤互变）',
        implication: '反复颠倒，往复不宁'),
  };
}
