import 'package:flutter_test/flutter_test.dart';
import 'package:wanxiang_paipan/domain/services/liuyao/analysis/liuyao_analyzer.dart';
import 'package:wanxiang_paipan/domain/services/liuyao/analysis/models/analysis_report.dart';

import 'helpers/analysis_fixtures.dart';

const _wangShuai = '旺衰/日月生克';
const _kongWang = '真空假空';
const _yuePo = '月破';
const _mu = '入墓/出墓';
const _he = '合住/合绊/化合';
const _huiTou = '回头生克';
const _jinTui = '化进退';
const _huaXuanZhi = '化空破墓绝';
const _shen = '元神/忌神/仇神';
const _fuShen = '飞伏/出伏';
const _yingQi = '应期条件联动';

class _GoldenCase {
  const _GoldenCase({
    required this.id,
    required this.nature,
    required this.question,
    required this.yueJian,
    required this.riGanZhi,
    required this.hexagram,
    required this.movingLines,
    required this.numbers,
    required this.position,
    required this.yongShen,
    required this.sourceChapter,
    required this.printedPages,
    required this.adjudication,
    required this.expectedTrend,
    required this.coverage,
    this.withChanging = false,
    this.isFuShen = false,
    this.expectedNuance,
    this.expectedConditions = const {},
    this.absentConditions = const {},
    this.expectedFactors = const {},
    this.expectedYingQiBranches = const {},
    this.hasUnrescuedCondition = false,
  });

  final int id;
  final String nature;
  final String question;
  final String yueJian;
  final String riGanZhi;
  final String hexagram;
  final String movingLines;
  final List<int> numbers;
  final int position;
  final String yongShen;
  final String sourceChapter;
  final String printedPages;
  final String adjudication;
  final VerdictTrend expectedTrend;
  final Set<String> coverage;
  final bool withChanging;
  final bool isFuShen;
  final String? expectedNuance;
  final Set<String> expectedConditions;
  final Set<String> absentConditions;
  final Set<String> expectedFactors;
  final Set<String> expectedYingQiBranches;
  final bool hasUnrescuedCondition;

  String get description => '例$id·$nature；问事：$question；$yueJian月$riGanZhi日；'
      '$hexagram（动爻：$movingLines）；取用：$yongShen；'
      '出处：《增删卜易·$sourceChapter》（《增删卜易（校对：中国男儿）》'
      '印刷页$printedPages）；裁定：$adjudication';
}

/// 领域覆盖矩阵。原书没有给出完整起卦数据的规则边界，均明确标作“章法校验例”。
///
/// 旺衰/空破：1-4, 6-9, 13-21, 29-32
/// 墓合化变：5, 7-8, 11-12, 15, 22-25, 28, 33-36
/// 元忌仇/飞伏：3-4, 6, 10, 14, 16, 26-27, 37-40
const _goldenCases = <_GoldenCase>[
  _GoldenCase(
    id: 1,
    nature: '章法校验例',
    question: '兄弟所谋能否成',
    yueJian: '申',
    riGanZhi: '戊戌',
    hexagram: '乾为天安静',
    movingLines: '无',
    numbers: [7, 7, 7, 7, 7, 7],
    position: 5,
    yongShen: '五爻兄弟申金',
    sourceChapter: '月将章、日辰章',
    printedPages: '27-30',
    adjudication: '申金临月建、戌日生金，生扶而无伤，断可成',
    expectedTrend: VerdictTrend.keCheng,
    expectedFactors: {'临月建'},
    coverage: {_wangShuai},
  ),
  _GoldenCase(
    id: 2,
    nature: '章法校验例',
    question: '求财能否得',
    yueJian: '未',
    riGanZhi: '辛未',
    hexagram: '坤为地安静',
    movingLines: '无',
    numbers: [8, 8, 8, 8, 8, 8],
    position: 5,
    yongShen: '五爻妻财亥水',
    sourceChapter: '旬空章',
    printedPages: '45-46',
    adjudication: '亥水受月日土克又旬空，休囚安静为真空，断难成',
    expectedTrend: VerdictTrend.nanCheng,
    expectedConditions: {'待出空'},
    hasUnrescuedCondition: true,
    coverage: {_wangShuai, _kongWang},
  ),
  _GoldenCase(
    id: 3,
    nature: '章法校验例',
    question: '谋官能否成',
    yueJian: '午',
    riGanZhi: '庚辰',
    hexagram: '震为雷之火雷噬嗑',
    movingLines: '三爻辰土独发',
    numbers: [7, 8, 6, 7, 8, 8],
    position: 5,
    yongShen: '五爻官鬼申金',
    sourceChapter: '元神、忌神、衰旺章；旬空章',
    printedPages: '22-23、45',
    adjudication: '申金月克逢空，得辰日及元神辰土动生，待出空而先难后成',
    expectedTrend: VerdictTrend.daiTiaoJian,
    expectedNuance: '先难后成',
    expectedConditions: {'待出空'},
    expectedFactors: {'动爻生'},
    expectedYingQiBranches: {'申'},
    withChanging: true,
    coverage: {_wangShuai, _kongWang, _shen, _yingQi},
  ),
  _GoldenCase(
    id: 4,
    nature: '章法校验例',
    question: '求财能否得',
    yueJian: '子',
    riGanZhi: '癸酉',
    hexagram: '乾为天之火天大有',
    movingLines: '五爻申金独发',
    numbers: [7, 7, 7, 7, 9, 7],
    position: 2,
    yongShen: '二爻妻财寅木',
    sourceChapter: '元神、忌神、衰旺章；五行相克章',
    printedPages: '22-25',
    adjudication: '财得月生但受酉日及旺动兄弟申金克，忌神独发，断难成',
    expectedTrend: VerdictTrend.nanCheng,
    expectedFactors: {'动爻克'},
    withChanging: true,
    coverage: {_wangShuai, _shen},
  ),
  _GoldenCase(
    id: 5,
    nature: '章法校验例',
    question: '功名能否成',
    yueJian: '午',
    riGanZhi: '丙寅',
    hexagram: '乾为天之风天小畜',
    movingLines: '四爻午火独发化未土',
    numbers: [7, 7, 7, 9, 7, 7],
    position: 4,
    yongShen: '四爻官鬼午火',
    sourceChapter: '六合章',
    printedPages: '32-33',
    adjudication: '午临月建得寅日生，午化未为化扶而非合绊，断可成',
    expectedTrend: VerdictTrend.keCheng,
    absentConditions: {'待冲开'},
    expectedFactors: {'化合'},
    withChanging: true,
    coverage: {_wangShuai, _he},
  ),
  _GoldenCase(
    id: 6,
    nature: '章法校验例',
    question: '兄弟所谋能否成',
    yueJian: '酉',
    riGanZhi: '戊辰',
    hexagram: '兑为泽之水泽节',
    movingLines: '初爻巳火独发',
    numbers: [9, 7, 8, 7, 7, 8],
    position: 5,
    yongShen: '五爻兄弟酉金',
    sourceChapter: '月将章；各门类应期总注章',
    printedPages: '28、48',
    adjudication: '用神临月建得日生，虽受巳火忌神动克，仍为吉中有阻',
    expectedTrend: VerdictTrend.daiTiaoJian,
    expectedNuance: '吉中有阻',
    expectedFactors: {'动爻克'},
    withChanging: true,
    coverage: {_wangShuai, _shen, _yingQi},
  ),
  _GoldenCase(
    id: 7,
    nature: '原书占例',
    question: '父何日归',
    yueJian: '辰',
    riGanZhi: '戊子',
    hexagram: '乾为天之泽天夬',
    movingLines: '上爻戌土独发化未土',
    numbers: [7, 7, 7, 7, 7, 9],
    position: 6,
    yongShen: '上爻父母戌土',
    sourceChapter: '月破章',
    printedPages: '50-51',
    adjudication: '父母月破而动又化空，原断卯日有信、未日归，待出月及变爻填实',
    expectedTrend: VerdictTrend.daiTiaoJian,
    expectedConditions: {'待出月', '待变爻填实'},
    expectedYingQiBranches: {'未'},
    withChanging: true,
    coverage: {_yuePo, _huaXuanZhi, _yingQi},
  ),
  _GoldenCase(
    id: 8,
    nature: '章法校验例',
    question: '谋官能否成',
    yueJian: '申',
    riGanZhi: '甲戌',
    hexagram: '坤为地之地雷复',
    movingLines: '三爻卯木独发化申金',
    numbers: [8, 8, 6, 8, 8, 8],
    position: 3,
    yongShen: '三爻官鬼卯木',
    sourceChapter: '动变生克冲合章；生旺墓绝章',
    printedPages: '26、47-48',
    adjudication: '官鬼月克休囚，回头克兼化绝，无救而难成',
    expectedTrend: VerdictTrend.nanCheng,
    expectedConditions: {'待长生扶起'},
    expectedFactors: {'回头克'},
    hasUnrescuedCondition: true,
    withChanging: true,
    coverage: {_wangShuai, _huiTou, _huaXuanZhi},
  ),
  _GoldenCase(
    id: 9,
    nature: '原书占例',
    question: '求财',
    yueJian: '寅',
    riGanZhi: '庚戌',
    hexagram: '火天大有安静',
    movingLines: '无',
    numbers: [7, 7, 7, 7, 8, 7],
    position: 2,
    yongShen: '二爻妻财寅木',
    sourceChapter: '月将章',
    printedPages: '28',
    adjudication: '财临月建，旬内仍空但非落底，原断甲寅日出空得财',
    expectedTrend: VerdictTrend.daiTiaoJian,
    expectedConditions: {'待出空'},
    expectedYingQiBranches: {'寅'},
    coverage: {_wangShuai, _kongWang, _yingQi},
  ),
  _GoldenCase(
    id: 10,
    nature: '章法校验例',
    question: '求财',
    yueJian: '子',
    riGanZhi: '甲子',
    hexagram: '天风姤安静',
    movingLines: '无',
    numbers: [8, 7, 7, 7, 7, 7],
    position: 2,
    yongShen: '二爻伏神妻财寅木',
    sourceChapter: '飞伏神章',
    printedPages: '52-54',
    adjudication: '飞神亥水生伏，伏神又得月日生，有力但尚伏，待值日或冲飞而出',
    expectedTrend: VerdictTrend.daiTiaoJian,
    expectedConditions: {'待出伏'},
    expectedFactors: {'飞生伏', '伏神得出'},
    expectedYingQiBranches: {'寅'},
    isFuShen: true,
    coverage: {_fuShen, _yingQi},
  ),
  _GoldenCase(
    id: 11,
    nature: '原书占例',
    question: '出门能否成行',
    yueJian: '申',
    riGanZhi: '丙子',
    hexagram: '地火明夷之雷山小过',
    movingLines: '初、四爻动',
    numbers: [9, 8, 7, 6, 8, 8],
    position: 4,
    yongShen: '四爻世爻官鬼丑土',
    sourceChapter: '六合章',
    printedPages: '33',
    adjudication: '世爻发动被子日合住，合住有事绊不能动身，待冲开；用神休囚而难成',
    expectedTrend: VerdictTrend.nanCheng,
    expectedConditions: {'待冲开'},
    expectedYingQiBranches: {'未'},
    withChanging: true,
    coverage: {_he, _yingQi},
  ),
  _GoldenCase(
    id: 12,
    nature: '原书占例',
    question: '弟已得重罪，兄能否救',
    yueJian: '卯',
    riGanZhi: '己卯',
    hexagram: '地雷复之震为雷',
    movingLines: '四爻丑土独发化午火',
    numbers: [7, 8, 8, 6, 8, 8],
    position: 4,
    yongShen: '四爻兄弟丑土',
    sourceChapter: '五行相生章',
    printedPages: '24',
    adjudication: '兄爻虽受日月克，幸化午火回头生；原断速救，后蒙恩免死',
    expectedTrend: VerdictTrend.keCheng,
    expectedFactors: {'回头生'},
    withChanging: true,
    coverage: {_wangShuai, _huiTou},
  ),
  _GoldenCase(
    id: 13,
    nature: '原书占例',
    question: '父官事已拟重罪',
    yueJian: '卯',
    riGanZhi: '戊辰',
    hexagram: '泽地萃之天火同人',
    movingLines: '初、三、上爻动',
    numbers: [6, 8, 6, 7, 7, 6],
    position: 6,
    yongShen: '上爻父母未土',
    sourceChapter: '五行相克章',
    printedPages: '25',
    adjudication: '父母未土受月克、日刑及亥卯未木局克，全无救助，后果重刑',
    expectedTrend: VerdictTrend.nanCheng,
    withChanging: true,
    coverage: {_wangShuai},
  ),
  _GoldenCase(
    id: 14,
    nature: '原书占例',
    question: '兄官事同案已拟重罪',
    yueJian: '卯',
    riGanZhi: '戊辰',
    hexagram: '天地否之天水讼',
    movingLines: '二爻巳火独发',
    numbers: [8, 6, 8, 7, 7, 7],
    position: 5,
    yongShen: '五爻兄弟申金',
    sourceChapter: '五行相克章、克处逢生章',
    printedPages: '25-26',
    adjudication: '巳火忌神克申，辰日冲戌父暗动生申，克处逢生，后援例免死',
    expectedTrend: VerdictTrend.daiTiaoJian,
    expectedNuance: '先难后成',
    expectedFactors: {'日生', '贪合忘克', '裁决·克处逢生'},
    withChanging: true,
    coverage: {_wangShuai, _shen},
  ),
  _GoldenCase(
    id: 15,
    nature: '原书占例',
    question: '新迁住宅后人口不安',
    yueJian: '卯',
    riGanZhi: '癸亥',
    hexagram: '水天需之乾为天',
    movingLines: '四、上爻动',
    numbers: [7, 7, 7, 6, 7, 6],
    position: 4,
    yongShen: '四爻世爻子孙申金',
    sourceChapter: '五行相克章',
    printedPages: '25',
    adjudication: '世爻申金化午火回头克，原断速迁；未迁而午月遭河决',
    expectedTrend: VerdictTrend.nanCheng,
    expectedFactors: {'回头克'},
    withChanging: true,
    coverage: {_huiTou, _huaXuanZhi},
  ),
  _GoldenCase(
    id: 16,
    nature: '原书占例',
    question: '弟痘症临危能否救',
    yueJian: '辰',
    riGanZhi: '丙申',
    hexagram: '水火既济之泽火革',
    movingLines: '四爻申金独发',
    numbers: [7, 8, 7, 6, 7, 8],
    position: 3,
    yongShen: '三爻世爻兄弟亥水',
    sourceChapter: '克处逢生章',
    printedPages: '26',
    adjudication: '月建辰土虽克亥水，得申日与申金动生，临危有救，后当日获医',
    expectedTrend: VerdictTrend.daiTiaoJian,
    expectedNuance: '先难后成',
    expectedFactors: {'日生', '动爻生'},
    withChanging: true,
    coverage: {_wangShuai, _shen},
  ),
  _GoldenCase(
    id: 17,
    nature: '原书占例',
    question: '远行求财能否成行',
    yueJian: '子',
    riGanZhi: '辛亥',
    hexagram: '山天大畜安静',
    movingLines: '无',
    numbers: [7, 7, 7, 8, 8, 7],
    position: 2,
    yongShen: '二爻世爻官鬼寅木（以世断能否成行）',
    sourceChapter: '旬空章',
    printedPages: '45-46',
    adjudication: '世空但得月日财水生，大象吉，原断甲寅出空后成行且满载而归',
    expectedTrend: VerdictTrend.daiTiaoJian,
    expectedConditions: {'待出空'},
    expectedYingQiBranches: {'寅'},
    coverage: {_wangShuai, _kongWang, _yingQi},
  ),
  _GoldenCase(
    id: 18,
    nature: '原书占例',
    question: '父何日回',
    yueJian: '寅',
    riGanZhi: '辛卯',
    hexagram: '风地观之天地否',
    movingLines: '四爻未土独发化午火',
    numbers: [8, 8, 8, 6, 7, 7],
    position: 4,
    yongShen: '四爻父母未土',
    sourceChapter: '旬空章',
    printedPages: '46',
    adjudication: '父爻虽真空且日月伤克，但动化回头生；就归期断未日出空而到',
    expectedTrend: VerdictTrend.daiTiaoJian,
    expectedConditions: {'待出空'},
    expectedFactors: {'回头生'},
    expectedYingQiBranches: {'未'},
    withChanging: true,
    coverage: {_kongWang, _huiTou, _yingQi},
  ),
  _GoldenCase(
    id: 19,
    nature: '原书占例',
    question: '将来有官否',
    yueJian: '亥',
    riGanZhi: '己丑',
    hexagram: '兑为泽之天水讼',
    movingLines: '初、上爻动',
    numbers: [9, 7, 8, 7, 7, 6],
    position: 1,
    yongShen: '初爻官鬼巳火',
    sourceChapter: '月破章',
    printedPages: '50',
    adjudication: '官鬼虽月破仍发动生世，出月实破后有用，原断实破巳年得官',
    expectedTrend: VerdictTrend.daiTiaoJian,
    expectedConditions: {'待出月'},
    expectedFactors: {'回头生'},
    withChanging: true,
    coverage: {_yuePo, _huiTou, _yingQi},
  ),
  _GoldenCase(
    id: 20,
    nature: '原书占例',
    question: '乡试能否中并联捷',
    yueJian: '申',
    riGanZhi: '癸卯',
    hexagram: '雷风恒之泽风大过',
    movingLines: '五爻申金独发化酉金',
    numbers: [8, 7, 7, 7, 6, 8],
    position: 3,
    yongShen: '三爻世爻官鬼酉金',
    sourceChapter: '进退章',
    printedPages: '55-56',
    adjudication: '官星持世旺相暗动，又得五爻官化进拱扶，原断今秋明春联捷',
    expectedTrend: VerdictTrend.keCheng,
    expectedFactors: {'动爻扶'},
    withChanging: true,
    coverage: {_wangShuai, _jinTui},
  ),
  _GoldenCase(
    id: 21,
    nature: '原书占例',
    question: '何年生子',
    yueJian: '酉',
    riGanZhi: '庚戌',
    hexagram: '水雷屯之水泽节',
    movingLines: '二爻寅木独发化卯木',
    numbers: [7, 6, 8, 8, 7, 8],
    position: 2,
    yongShen: '二爻世爻子孙寅木',
    sourceChapter: '进退章',
    printedPages: '55-56',
    adjudication: '子孙化进，动爻旬空、变爻空破，待寅卯年实空实破后连生',
    expectedTrend: VerdictTrend.daiTiaoJian,
    expectedConditions: {'待出空', '待变爻填实', '待变爻出月填实'},
    expectedFactors: {'化进神'},
    expectedYingQiBranches: {'寅', '卯'},
    withChanging: true,
    coverage: {_kongWang, _yuePo, _jinTui, _huaXuanZhi, _yingQi},
  ),
  _GoldenCase(
    id: 22,
    nature: '原书占例',
    question: '求婚成否',
    yueJian: '卯',
    riGanZhi: '乙丑',
    hexagram: '火雷噬嗑之水地比',
    movingLines: '初、四、五、上爻动',
    numbers: [9, 8, 8, 9, 6, 9],
    position: 5,
    yongShen: '五爻世爻妻财未土',
    sourceChapter: '进退章',
    printedPages: '56',
    adjudication: '财持世化进，子孙巳火动生世，待午日冲去回头克子水后允婚',
    expectedTrend: VerdictTrend.daiTiaoJian,
    expectedConditions: {'待变爻填实'},
    expectedFactors: {'化进神', '动爻生'},
    withChanging: true,
    coverage: {_jinTui, _huaXuanZhi, _shen, _yingQi},
  ),
  _GoldenCase(
    id: 23,
    nature: '原书占例',
    question: '被论后自陈能否免祸',
    yueJian: '酉',
    riGanZhi: '甲辰',
    hexagram: '地水师之地火明夷',
    movingLines: '初、二、三爻动',
    numbers: [6, 9, 6, 8, 8, 8],
    position: 3,
    yongShen: '三爻世爻妻财午火',
    sourceChapter: '进退章',
    printedPages: '56',
    adjudication: '世爻化亥水回头克，官退、子进亦非吉，原断大凶后革职拿问',
    expectedTrend: VerdictTrend.nanCheng,
    expectedFactors: {'回头克'},
    withChanging: true,
    coverage: {_huiTou, _jinTui},
  ),
  _GoldenCase(
    id: 24,
    nature: '原书占例',
    question: '父已起程，前往迎接能否相遇',
    yueJian: '丑',
    riGanZhi: '丙戌',
    hexagram: '水山蹇之火山旅',
    movingLines: '四、五、上爻动',
    numbers: [8, 8, 7, 6, 9, 6],
    position: 5,
    yongShen: '五爻父母戌土',
    sourceChapter: '进退章',
    printedPages: '56-57',
    adjudication: '父化退表示已归，变爻未土空破，待未日实空实破而相逢',
    expectedTrend: VerdictTrend.daiTiaoJian,
    expectedConditions: {'待变爻填实', '待变爻出月填实'},
    expectedFactors: {'化退神'},
    expectedYingQiBranches: {'未'},
    withChanging: true,
    coverage: {_jinTui, _huaXuanZhi, _yingQi},
  ),
  _GoldenCase(
    id: 25,
    nature: '原书占例',
    question: '冬令能否得官差',
    yueJian: '戌',
    riGanZhi: '癸巳',
    hexagram: '水泽节之水天需',
    movingLines: '三爻丑土独发化辰土',
    numbers: [7, 7, 6, 8, 7, 8],
    position: 3,
    yongShen: '三爻官鬼丑土',
    sourceChapter: '进退章',
    printedPages: '57',
    adjudication: '官鬼丑土化辰土进神，变爻辰受戌月冲破，待填实后丑月得官差',
    expectedTrend: VerdictTrend.daiTiaoJian,
    expectedConditions: {'待变爻出月填实'},
    expectedFactors: {'化进神'},
    expectedYingQiBranches: {'辰'},
    withChanging: true,
    coverage: {_jinTui, _huaXuanZhi, _yingQi},
  ),
  _GoldenCase(
    id: 26,
    nature: '原书占例',
    question: '妻病服药可愈否',
    yueJian: '丑',
    riGanZhi: '癸卯',
    hexagram: '地泽临之地天泰',
    movingLines: '三爻丑土独发化辰土',
    numbers: [7, 7, 6, 8, 8, 8],
    position: 5,
    yongShen: '五爻妻财亥水',
    sourceChapter: '进退章',
    printedPages: '57',
    adjudication: '忌神兄弟丑土临月建发动化进，克财有力，原断灵丹莫救',
    expectedTrend: VerdictTrend.nanCheng,
    withChanging: true,
    coverage: {_jinTui, _shen},
  ),
  _GoldenCase(
    id: 27,
    nature: '原书占例',
    question: '流年病势（校对本异文）',
    yueJian: '辰',
    riGanZhi: '癸丑',
    hexagram: '泽水困之雷水解',
    movingLines: '五爻酉金独发化申金',
    numbers: [8, 7, 8, 7, 9, 8],
    position: 1,
    yongShen: '初爻世爻妻财寅木',
    sourceChapter: '进退章',
    printedPages: '58',
    adjudication: '世空待出空，旺动忌神酉金虽化退仍受三土生，出空后遭克，原断凶',
    expectedTrend: VerdictTrend.nanCheng,
    expectedConditions: {'待出空'},
    withChanging: true,
    coverage: {_kongWang, _jinTui, _shen},
  ),
  _GoldenCase(
    id: 28,
    nature: '原书占例',
    question: '妻母病势',
    yueJian: '辰',
    riGanZhi: '乙丑',
    hexagram: '泽雷随之天地否',
    movingLines: '初、上爻动',
    numbers: [9, 8, 8, 7, 7, 6],
    position: 1,
    yongShen: '初爻父母子水',
    sourceChapter: '进退章',
    printedPages: '58-59',
    adjudication: '父母子水动化未土回头克，上爻未土又化进增克，原断戌日危',
    expectedTrend: VerdictTrend.nanCheng,
    expectedFactors: {'回头克'},
    withChanging: true,
    coverage: {_huiTou, _jinTui},
  ),
  _GoldenCase(
    id: 29,
    nature: '原书占例',
    question: '出行能否顺遂',
    yueJian: '申',
    riGanZhi: '乙卯',
    hexagram: '水雷屯之水泽节',
    movingLines: '二爻寅木独发化卯木',
    numbers: [7, 6, 8, 8, 7, 8],
    position: 2,
    yongShen: '二爻世爻子孙寅木',
    sourceChapter: '进退章',
    printedPages: '59',
    adjudication: '世化进但临月破，目下不行，待亥月破逢合后成行且往返平安',
    expectedTrend: VerdictTrend.daiTiaoJian,
    expectedConditions: {'待出月'},
    expectedFactors: {'化进神'},
    withChanging: true,
    coverage: {_yuePo, _jinTui, _yingQi},
  ),
  _GoldenCase(
    id: 30,
    nature: '原书占例',
    question: '兄何时归',
    yueJian: '辰',
    riGanZhi: '己未',
    hexagram: '天泽履之兑为泽',
    movingLines: '上爻戌土独发化未土',
    numbers: [7, 7, 8, 7, 7, 9],
    position: 6,
    yongShen: '上爻兄弟戌土',
    sourceChapter: '进退章',
    printedPages: '59',
    adjudication: '兄动化退已有归志，但戌临月破，待实破戌月方归',
    expectedTrend: VerdictTrend.daiTiaoJian,
    expectedConditions: {'待出月'},
    expectedFactors: {'化退神'},
    withChanging: true,
    coverage: {_yuePo, _jinTui, _yingQi},
  ),
  _GoldenCase(
    id: 31,
    nature: '原书占例',
    question: '官府可升否',
    yueJian: '卯',
    riGanZhi: '丙申',
    hexagram: '雷水解之泽水困',
    movingLines: '五爻申金独发化酉金',
    numbers: [8, 8, 7, 7, 6, 8],
    position: 5,
    yongShen: '五爻官鬼申金',
    sourceChapter: '进退章',
    printedPages: '59',
    adjudication: '官临日建发动化进，原断秋令必迁，后巳月因动逢合而升',
    expectedTrend: VerdictTrend.daiTiaoJian,
    expectedConditions: {'待变爻出月填实'},
    expectedFactors: {'化进神', '临日建'},
    withChanging: true,
    coverage: {_wangShuai, _jinTui, _yingQi},
  ),
  _GoldenCase(
    id: 32,
    nature: '原书占例',
    question: '开金银器皿铺能否兴盛',
    yueJian: '未',
    riGanZhi: '辛未',
    hexagram: '火雷噬嗑之水雷屯',
    movingLines: '四、五、上爻动',
    numbers: [7, 8, 8, 9, 6, 9],
    position: 5,
    yongShen: '五爻世爻妻财未土',
    sourceChapter: '进退章',
    printedPages: '60',
    adjudication: '财临日月持世化进，变爻戌空，待甲戌填实开张后长久兴盛',
    expectedTrend: VerdictTrend.daiTiaoJian,
    expectedConditions: {'待变爻填实'},
    expectedFactors: {'化进神', '临月建'},
    expectedYingQiBranches: {'戌'},
    withChanging: true,
    coverage: {_wangShuai, _jinTui, _huaXuanZhi, _yingQi},
  ),
  _GoldenCase(
    id: 33,
    nature: '原书占例',
    question: '夫病能否愈',
    yueJian: '申',
    riGanZhi: '戊辰',
    hexagram: '天火同人之离为火',
    movingLines: '五爻申金独发',
    numbers: [7, 8, 7, 7, 9, 7],
    position: 3,
    yongShen: '三爻世爻官鬼亥水',
    sourceChapter: '随鬼入墓章',
    printedPages: '61-62',
    adjudication: '亥水入辰日墓又旬空，但得申月及申金动生，原断次日冲起即愈',
    expectedTrend: VerdictTrend.daiTiaoJian,
    expectedConditions: {'待出空', '待冲开墓库'},
    expectedFactors: {'月生', '动爻生'},
    expectedYingQiBranches: {'亥', '戌'},
    withChanging: true,
    coverage: {_kongWang, _mu, _shen, _yingQi},
  ),
  _GoldenCase(
    id: 34,
    nature: '原书占例',
    question: '会试能否联捷',
    yueJian: '戌',
    riGanZhi: '甲寅',
    hexagram: '雷山小过之艮为山',
    movingLines: '四、上爻动',
    numbers: [8, 8, 7, 9, 8, 6],
    position: 4,
    yongShen: '四爻世爻官鬼午火',
    sourceChapter: '随鬼入墓章',
    printedPages: '61-62',
    adjudication: '官旺得寅日生，虽入月墓且化墓，待辰年辰月冲开三墓后联捷',
    expectedTrend: VerdictTrend.daiTiaoJian,
    expectedConditions: {'待冲开墓库', '待冲开化墓'},
    expectedYingQiBranches: {'辰'},
    withChanging: true,
    coverage: {_mu, _huaXuanZhi, _yingQi},
  ),
  _GoldenCase(
    id: 35,
    nature: '章法校验例',
    question: '功名墓库已逢冲能否成',
    yueJian: '寅',
    riGanZhi: '甲辰',
    hexagram: '乾为天之泽天夬',
    movingLines: '上爻戌土独发；四爻午火入动墓而辰日冲墓',
    numbers: [7, 7, 7, 7, 7, 9],
    position: 4,
    yongShen: '四爻官鬼午火',
    sourceChapter: '生旺墓绝章；各门类应期总注章',
    printedPages: '47-48',
    adjudication: '午火得寅月生，虽入戌动墓但辰日已冲开，出墓后不再悬置',
    expectedTrend: VerdictTrend.keCheng,
    absentConditions: {'待冲开墓库'},
    withChanging: true,
    coverage: {_mu, _yingQi},
  ),
  _GoldenCase(
    id: 36,
    nature: '章法校验例',
    question: '合作之事能否立即推进',
    yueJian: '子',
    riGanZhi: '乙卯',
    hexagram: '地天泰之水风井',
    movingLines: '初爻子水、四爻丑土同动相合',
    numbers: [9, 7, 7, 6, 8, 8],
    position: 1,
    yongShen: '初爻妻财子水',
    sourceChapter: '六合章；各门类应期总注章',
    printedPages: '32-33、48',
    adjudication: '用神临月建但两动相合为合绊，须待午冲子解绊后再推进',
    expectedTrend: VerdictTrend.daiTiaoJian,
    expectedConditions: {'待冲开'},
    expectedYingQiBranches: {'午'},
    withChanging: true,
    coverage: {_he, _yingQi},
  ),
  _GoldenCase(
    id: 37,
    nature: '章法校验例',
    question: '伏神受飞神压制能否得用',
    yueJian: '午',
    riGanZhi: '甲辰',
    hexagram: '天山遁安静',
    movingLines: '无',
    numbers: [8, 8, 7, 7, 7, 7],
    position: 1,
    yongShen: '初爻伏神子孙子水',
    sourceChapter: '飞伏神章',
    printedPages: '52-54',
    adjudication: '飞神辰土克伏神子水，伏藏而受制，出伏无解，断难成',
    expectedTrend: VerdictTrend.nanCheng,
    expectedConditions: {'待出伏'},
    expectedFactors: {'飞克伏'},
    hasUnrescuedCondition: true,
    isFuShen: true,
    coverage: {_fuShen},
  ),
  _GoldenCase(
    id: 38,
    nature: '章法校验例',
    question: '飞神被日冲后伏神能否出',
    yueJian: '申',
    riGanZhi: '甲戌',
    hexagram: '天山遁安静',
    movingLines: '无；戌日冲初爻飞神辰土',
    numbers: [8, 8, 7, 7, 7, 7],
    position: 1,
    yongShen: '初爻伏神子孙子水',
    sourceChapter: '飞伏神章',
    printedPages: '52-54',
    adjudication: '日冲飞神而伏神得出，虽仍待值日引出，出伏已有解救路径',
    expectedTrend: VerdictTrend.daiTiaoJian,
    expectedConditions: {'待出伏'},
    expectedFactors: {'伏神得出'},
    expectedYingQiBranches: {'子'},
    isFuShen: true,
    coverage: {_fuShen, _yingQi},
  ),
  _GoldenCase(
    id: 39,
    nature: '章法校验例',
    question: '仇神生忌、忌神接续克用时能否成',
    yueJian: '子',
    riGanZhi: '乙卯',
    hexagram: '乾为天之山泽损',
    movingLines: '二爻寅木仇神、四爻午火忌神同动',
    numbers: [7, 9, 7, 9, 7, 7],
    position: 5,
    yongShen: '五爻兄弟申金',
    sourceChapter: '用神、元神、忌神、仇神章；元神、忌神、衰旺章',
    printedPages: '21-23',
    adjudication: '寅木仇神生午火忌神，午火动克申金，用神无日月强扶，断难成',
    expectedTrend: VerdictTrend.nanCheng,
    expectedFactors: {'动爻克'},
    withChanging: true,
    coverage: {_shen},
  ),
  _GoldenCase(
    id: 40,
    nature: '章法校验例',
    question: '只有飞神生伏而无日月扶助时能否立即得用',
    yueJian: '午',
    riGanZhi: '乙丑',
    hexagram: '天风姤安静',
    movingLines: '无',
    numbers: [8, 7, 7, 7, 7, 7],
    position: 2,
    yongShen: '二爻伏神妻财寅木',
    sourceChapter: '飞伏神章',
    printedPages: '52-54',
    adjudication: '飞神亥水生伏但无日月生扶，只能证明出伏有源，仍须等待伏神引出',
    expectedTrend: VerdictTrend.daiTiaoJian,
    expectedConditions: {'待出伏'},
    expectedFactors: {'飞生伏'},
    expectedYingQiBranches: {'寅'},
    isFuShen: true,
    coverage: {_fuShen, _yingQi},
  ),
];

const _coverageFloor = <String, int>{
  _wangShuai: 10,
  _kongWang: 6,
  _yuePo: 5,
  _mu: 3,
  _he: 3,
  _huiTou: 7,
  _jinTui: 12,
  _huaXuanZhi: 8,
  _shen: 9,
  _fuShen: 4,
  _yingQi: 18,
};

void main() {
  AnalysisReport run(_GoldenCase goldenCase) {
    final gua = buildGua(goldenCase.numbers);
    return LiuYaoAnalyzer.analyze(
      gua,
      goldenCase.withChanging ? buildChangingGua(gua) : null,
      buildLunar(
        yueJian: goldenCase.yueJian,
        riGanZhi: goldenCase.riGanZhi,
      ),
      yongShenPosition: goldenCase.position,
      yongShenIsFuShen: goldenCase.isFuShen,
    );
  }

  group('黄金断例领域覆盖矩阵', () {
    test('至少40例且各规则域达到覆盖下限', () {
      expect(_goldenCases, hasLength(greaterThanOrEqualTo(40)));
      expect(_goldenCases.map((c) => c.id).toSet(),
          hasLength(_goldenCases.length));

      for (final entry in _coverageFloor.entries) {
        final actual =
            _goldenCases.where((c) => c.coverage.contains(entry.key)).length;
        expect(actual, greaterThanOrEqualTo(entry.value),
            reason: '${entry.key}覆盖仅$actual例，低于下限${entry.value}');
      }
    });

    test('每例均记录完整占例元数据，规则推导不冒充原书占例', () {
      for (final goldenCase in _goldenCases) {
        expect(goldenCase.question, isNotEmpty, reason: '例${goldenCase.id}');
        expect(goldenCase.hexagram, isNotEmpty, reason: '例${goldenCase.id}');
        expect(goldenCase.movingLines, isNotEmpty, reason: '例${goldenCase.id}');
        expect(goldenCase.yongShen, isNotEmpty, reason: '例${goldenCase.id}');
        expect(goldenCase.sourceChapter, isNotEmpty,
            reason: '例${goldenCase.id}');
        expect(goldenCase.printedPages, isNotEmpty,
            reason: '例${goldenCase.id}');
        expect(
          goldenCase.nature,
          anyOf('原书占例', '章法校验例'),
          reason: '例${goldenCase.id}必须明确来源性质',
        );
      }
    });
  });

  group('黄金断例（《增删卜易》裁决矩阵）', () {
    for (final goldenCase in _goldenCases) {
      test(goldenCase.description, () {
        final report = run(goldenCase);
        final judgment = report.judgment!;
        final conditionLabels = judgment.conditions.map((c) => c.label).toSet();
        final factorRules = judgment.factors.map((f) => f.rule).toSet();
        final yingQiBranches = report.yingQi!.map((c) => c.branch).toSet();

        expect(judgment.trend, goldenCase.expectedTrend);
        if (goldenCase.expectedNuance != null) {
          expect(judgment.nuance, goldenCase.expectedNuance);
        }
        expect(conditionLabels, containsAll(goldenCase.expectedConditions));
        for (final absent in goldenCase.absentConditions) {
          expect(conditionLabels, isNot(contains(absent)));
        }
        expect(factorRules, containsAll(goldenCase.expectedFactors));
        expect(
          yingQiBranches,
          containsAll(goldenCase.expectedYingQiBranches),
          reason: '未决条件必须能在应期候选中找到对应地支',
        );
        if (goldenCase.hasUnrescuedCondition) {
          expect(judgment.conditions.any((c) => !c.hasRescue), isTrue);
        }
      });
    }
  });
}
